Models/Tournament/AddTournamentFormModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TennisTournament.Data.Models;

namespace TennisTournament.Models.Tournament
{
    public class AddTournamentFormModel
    {
        [Required]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "Name must be in range 3-60 characters!")]
        public string Name { get; init; }

        [Required]
        public GameType GameTypes { get; set; }

        [Required]
        public CourtType CourtTypes { get; set; }

        [Required]
        public Set Sets { get; set; }

        [Required]
        public Game Games { get; set; }

        [Required]
        public Rule Rules { get; set; }

        [Required]
        public LastSet LastSets { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 10, ErrorMessage = "Description must be in range 10-255 characters!")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please choose photo to upload.")]
        [Display(Name = "Upload photo")]
        public IFormFile CoverPhoto { get; set; }
    }
}

Models/Tournament/AllTournamentsQueryModel.cs
using System.ComponentModel.DataAnnotations;
using TennisTournament.Data.Models;
using TennisTournament.Services.Players;
using TennisTournament.Services.Tournaments;

namespace TennisTournament.Models.Tournament
{
    public class AllTournamentsQueryModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public double? MinRank { get; set; }

        [Display(Name = "Game type:")]
        public GameType GameType { get; set; }

        [Display(Name = "Court type:")]
        public CourtType CourtType { get; set; }

        public Set Set { get; set; }

        public Game Game { get; set; }

        public Rule Rule { get; set; }

        public LastSet LastSet { get; set; }

        [Display(Name = "Search:")]
        public string SearchTerm { get; set; }

        [Display(Name = "Image:")]
        public string CoverPhoto { get; set; }

        [Display(Name = "Description:")]
        public string Description { get; set; }

        public int TotalTournaments { get; set; }

        public ICollection<TournamentServiceModel> Tournaments { get; set; }

        public ICollection<PlayerServiceModel> Players { get; set; }

        public int PlayerId { get; set; }
    }
}

Models/Tournament/TournamentFormModel.cs
using System.ComponentModel.DataAnnotations;
using TennisTournament.Data.Models;

namespace TennisTournament.Models.Tournament
{
    public class TournamentFormModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "Name must be in range 3-60 characters!")]
        public string Name { get; init; }

        public double? MinRank { get; set; }

        [Required]
        public GameType GameType { get; set; }

        [Required]
        public CourtType CourtType { get; set; }

        [Required]
        public Set Set { get; set; }

        [Required]
        public Game Game { get; set; }

        [Required]
        public Rule Rule { get; set; }

        [Required]
        public LastSet LastSet { get; set; }

        [Required]
        public DateTime StartDate { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 10, ErrorMessage = "Description must be in range 10-255 characters!")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please choose photo to upload.")]
        [Display(Name = "Upload photo")]
        public IFormFile CoverPhoto { get; set; }
    }
}

Models/Tournament/TournamentListingViewModel.cs
using TennisTournament.Data.Models;

namespace TennisTournament.Models.Tournament
{
    public class TournamentListingViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public GameType GameType { get; set; }

        public CourtType CourtType { get; set; }

        public string Description { get; set; }

        public string CoverPhoto { get; set; }
    }
}

Models/Tournament/TypeOfGameViewModel.cs
namespace TennisTournament.Models.Tournament
{
    public class TypeOfGameViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Controllers/Tournament/MatchController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TennisTournament.Data.Models;
using TennisTournament.Models.Match;
using TennisTournament.Services.Matches;
using TennisTournament.Services.Matches.Models;

namespace TennisTournament.Controllers
{
    public class MatchController : Controller
    {
        private readonly IMatchService matchService;

        public MatchController(IMatchService matchService)
        {
            this.matchService = matchService;
        }

        [Authorize]
        public IActionResult CreateMatch(MatchServiceModel match, int tournamentId)
        {
            if (!ModelState.IsValid)
            {
                return View(match);
            }

            var matchData = new Match
            {
                FirstPlayerId = match.FirstPlayerId,
                SecondPlayerId = match.SecondPlayerId,
                TournamentId = tournamentId
            };

            this.matchService.CreateMatch(match, tournamentId);

            return RedirectToAction("All", "Tournament");
        }

        public IActionResult Details(int id)
        {
            var match = this.matchService.Details(id);

            return View(new MatchServiceModel
            {
                Id = match.Id,
                FirstPlayerId = match.FirstPlayerId,
                SecondPlayerId = match.SecondPlayerId,
                TournamentId = match.TournamentId
            });
        }

        [Authorize]
        public IActionResult ResultMatch(MatchWinnerFormModel winnerModel, int matchId)
        {
            this.matchService.MatchResult(matchId, winnerModel.WinnerId);

            return RedirectToAction("All", "Player");
        }
    }
}

Controllers/Tournament/RoundController.cs
using Microsoft.AspNetCore.Mvc;

namespace TennisTournament.Controllers
{
    public class RoundController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/Tournament/TournamentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TennisTournament.Data.Models;
using TennisTournament.Infrastructure;
using TennisTournament.Models.Tournament;
using TennisTournament.Services;
using TennisTournament.Services.Players;
using TennisTournament.Services.Tournaments;

namespace TennisTournament.Controllers
{
    public class TournamentController : Controller
    {
        private readonly ITournamentService tournamentService;
        private readonly IPlayerService playerService;
        private readonly IUploadFileService uploadFileService;

        public TournamentController(
            ITournamentService tournaments,
            IPlayerService playerService,
            IUploadFileService uploadFile)
        {
            this.tournamentService = tournaments;
            this.playerService = playerService;
            this.uploadFileService = uploadFile;
        }

        public async Task<IActionResult> Bracket(int id)
        {
            var bracket = await this.tournamentService.DetailsAsync(id);

            return View(new TournamentServiceModel
            {
                Id = id,
                Name = bracket.Name,
                MinRank = bracket.MinRank,
                CourtType = bracket.CourtType,
                GameType = bracket.GameType,
                Game = bracket.Game,
                Set = bracket.Set,
                Rule = bracket.Rule,
                LastSet = bracket.LastSet,
                StartDate = bracket.StartDate,
                Description = bracket.Description,
                CoverPhoto = bracket.CoverPhoto,
                Players = bracket.Players,
                Matches = bracket.Matches
            });
        }

        [HttpGet]
        [Authorize]
        public IActionResult AddPlayerToTournament(int tournamentId)
        {
            if (!UserIsPlayer())
            {
                return RedirectToAction("AddPlayer", "Player");
            }

            this.tournamentService.AddPlayerToTournament(this.User.GetId(), tournamentId);

            return RedirectToAction("All", "Player");
        }

        [HttpGet]
        [Authorize]
        public IActionResult RemovePlayerFromTournament(int tournamentId)
        {
            this.tournamentService.RemovePlayerFromTournament(this.User.GetId(), tournamentId);

            return RedirectToAction("All", "Player");

        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var tournament = await this.tournamentService.DetailsAsync(id);

            return View(new TournamentFormModel
            {
                Name = tournament.Name,
                MinRank = tournament.MinRank,
                GameType = tournament.GameType,
                CourtType = tournament.CourtType,
                Set = tournament.Set,
                Game = tournament.Game,
                Rule = tournament.Rule,
                LastSet = tournament.LastSet,
                StartDate = tournament.StartDate,
                Description = tournament.Description
            });
        }

        [HttpPost]
        [Authorize] 
        public async Task<IActionResult> Edit(int id, TournamentFormModel tournament)
        {
            if (!ModelState.IsValid)
            {
                return View(tournament);
            }


            string coverPhoto = this.UploadCoverPhoto(tournament.CoverPhoto);

            var tournamentIsEdited = await this.tournamentService.EditAsync(
                id,
                tournament.Name,
                tournament.MinRank,
                tournament.CourtType,
                tournament.GameType,
                tournament.Set,
                tournament.Game,
                tournament.Rule,
                tournament.LastSet,
                tournament.StartDate,
                tournament.Description);

            if (!tournamentIsEdited)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Details(int id)
        {
            var tournament = await this.tournamentService.DetailsAsync(id);

            return View(new TournamentServiceModel
            {
                Id = id,
                Name = tournament.Name,
                MinRank = tournament.MinRank,
                CourtType = tournament.CourtType,
                GameType = tournament.GameType,
                Game = tournament.Game,
                Set = tournament.Set,
                Rule = tournament.Rule,
                LastSet = tournament.LastSet,
                StartDate = tournament.StartDate,
                Description = tournament.Description,
                CoverPhoto = tournament.CoverPhoto,
                Players = tournament.Players,
                Matches = tournament.Matches
            });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var deleted = await this.tournamentService.DeleteAsync(id);

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> All([FromQuery]AllTournamentsQueryModel query)
        {
            var queryResult = await this.tournamentService.AllAsync(
                query.Name,
                query.SearchTerm,
                query.CourtType,
                query.GameType);

            query.TotalTournaments = queryResult.TotalTournaments;
            query.Tournaments = queryResult.Tournaments;

            return View(query);
        }

        [Authorize]
        public IActionResult AddTournament()
        {
            return View(new TournamentFormModel());
        }

        [HttpPost]
        [Authorize]
        [RequestFormLimits(MultipartBodyLengthLimit = 5242880)]
        [RequestSizeLimit(5242880)]
        public IActionResult AddTournament(TournamentFormModel tournament)
        {
            if (!ModelState.IsValid)
            {
                return View(tournament);
            }

            if (tournament.CoverPhoto == null || !(tournament.CoverPhoto.FileName.EndsWith(".jpg")))
            {
                return View(tournament);
            }

            string coverPhoto = this.UploadCoverPhoto(tournament.CoverPhoto);

            var tournamentData = new Tournament
            {
                Name = tournament.Name,
                MinRank = tournament.MinRank,
                GameType = tournament.GameType,
                CourtType = tournament.CourtType,
                Set = tournament.Set,
                Game = tournament.Game,
                Rule = tournament.Rule,
                LastSet = tournament.LastSet,
                StartDate = tournament.StartDate,
                Description = tournament.Description,
                CoverPhoto = coverPhoto,
            };

            this.tournamentService.CreateTournament(tournament, coverPhoto);

            return RedirectToAction(nameof(All));
        }

        public bool UserIsPlayer()
        {
            var userId = this.User.GetId();

            return this.playerService.UserIsPlayer(userId);
        }

        private string UploadCoverPhoto(IFormFile coverPhoto)
        {
            var photo = this.uploadFileService.CoverPhoto(coverPhoto);

            return photo;
        }
    }
}

Views/Tournament/Add.cshtml
@model TournamentFormModel

@{
    ViewBag.Title = "Add Tournament";
}

@if (User.IsInRole(Roles.Administrator))
{
    <partial name="_TournamentFormPartial" model="@Model" />
}

Views/Tournament/AddTournament.cshtml
@model TournamentFormModel

@{
    ViewBag.Title = "Add Tournament";
}

@if (User.IsInRole(Roles.Administrator))
{
    <partial name="_TournamentFormPartial" model="@Model" />
}

Views/Tournament/Bracket.cshtml
@model TournamentServiceModel

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Holtwood+One+SC' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script|Herr+Von+Muellerhoff' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Istok+Web|Roboto+Condensed:700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/css/bracket.css" asp-append-version="true" />

    <title>March Madness Stock Matchup</title>
</head>
<body>
    <header class="hero">
        <div class="hero-wrap">
            <p class="intro" id="intro">@Model.GameType</p>
            <h1 id="headline">@Model.Name</h1>
            <p class="year"><i class="fa fa-star"></i>@Model.StartDate<i class="fa fa-star"></i></p>
            <p>@Model.Description</p>
        </div>
    </header>
    <section id="bracket">
        <div class="container">
            <div class="split split-one">
                <div class="round round-one current">
                    <div class="round-details">Round 1<br /><span class="date">@Model.StartDate</span></div>
                    @foreach (var match in Model.Matches)
                    {
                        var firstPlayer = Model.Players.FirstOrDefault(p => p.Id == match.FirstPlayerId);
                        var secondPlayer = Model.Players.FirstOrDefault(p => p.Id == match.SecondPlayerId);

                        <ul class="matchup">
                            <a asp-controller="Match" asp-action="Details" asp-route-id="@match.Id" />
                            <li class="team team-top">@firstPlayer.Name<span class="score">@firstPlayer.Rank</span></li>
                            <li class="team team-top">@secondPlayer.Name<span class="score">@secondPlayer.Rank</span></li>
                        </ul>
                    }
                </div>

                <div class="round round-two">
                    <div class="round-details">Round 2</div>

                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                </div>  

                <div class="round round-three">
                    <div class="round-details">Round 3</div>

                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                </div>
            </div>

            <div class="champion">
                <div class="semis-l">
                    <div class="round-details">west semifinals</div>
                    <ul class="matchup championship">
                        <li class="team team-top">&nbsp;<span class="vote-count">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="vote-count">&nbsp;</span></li>
                    </ul>
                </div>
                <div class="final">
                    <i class="fa fa-trophy"></i>
                    <div class="round-details">championship</div>
                    <ul class="matchup championship">
                        <li class="team team-top">&nbsp;<span class="vote-count">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="vote-count">&nbsp;</span></li>
                    </ul>
                </div>
            </div>


            <div class="split split-two">


                <div class="round round-three">
                    <div class="round-details">Round 3<br /><span class="date">March 22</span></div>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                </div>  <!-- END ROUND THREE -->

                <div class="round round-two">
                    <div class="round-details">Round 2<br /><span class="date">March 18</span></div>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">&nbsp;<span class="score">&nbsp;</span></li>
                        <li class="team team-bottom">&nbsp;<span class="score">&nbsp;</span></li>
                    </ul>
                </div>  <!-- END ROUND TWO -->
                <div class="round round-one current">
                    <div class="round-details">Round 1<br /><span class="date">March 16</span></div>
                    <ul class="matchup">
                        <li class="team team-top">Minnesota<span class="score">62</span></li>
                        <li class="team team-bottom">Northwestern<span class="score">54</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">Michigan<span class="score">68</span></li>
                        <li class="team team-bottom">Iowa<span class="score">66</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">Illinois<span class="score">64</span></li>
                        <li class="team team-bottom">Wisconsin<span class="score">56</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">Purdue<span class="score">36</span></li>
                        <li class="team team-bottom">Boise State<span class="score">40</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">Penn State<span class="score">38</span></li>
                        <li class="team team-bottom">Indiana<span class="score">44</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">Ohio State<span class="score">52</span></li>
                        <li class="team team-bottom">VCU<span class="score">80</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">USC<span class="score">58</span></li>
                        <li class="team team-bottom">Cal<span class="score">59</span></li>
                    </ul>
                    <ul class="matchup">
                        <li class="team team-top">Virginia Tech<span class="score">74</span></li>
                        <li class="team team-bottom">Dartmouth<span class="score">111</span></li>
                    </ul>
                </div>  <!-- END ROUND ONE -->
            </div>
        </div>
    </section>
</body>

Views/Tournament/Details.cshtml
@model TournamentServiceModel

@{
    ViewBag.Title = "Details";
}

<h1 class="text-color-green text-center">@ViewBag.Title</h1>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/details-form.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/joined-players.css" asp-append-version="true" />

<div class="container emp-profile">
    <div class="row">
        <div class="col-md-4">
            <div class="profile-img">
                <img src="/UploadedPhotos/CoverPhotos/@Model.CoverPhoto" class="img img-responsive">
            </div>
        </div>
        <div class="col-md-6">
            <div class="profile-head">
                <h5>
                    @Model.Name
                </h5>
                <h6>
                    Professional tennis player
                </h6>
                <p class="proile-rating">Max Rank: @Model.MinRank<span></span></p>
                <p class="proile-rating">Start Date: @Model.StartDate<span></span></p>
                <ul class="nav nav-tabs" id="myTab" role="tablist" />
            </div>
        </div>
        <div class="col-md-2">
            <div class="row mb-2">
                @if (User.IsInRole(Roles.Administrator))
                {
                    <a asp-controller="Tournament" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
                    <a asp-controller="Tournament" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger mt-3">Delete</a>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="profile-work">
                <p>Achievements</p>
                <a href="">1st - Gold Medal</a><br />
                <a href="">2nd - Silver Medal</a><br />
                <a href="">3rd - Bronze Medal</a><br />
            </div>
        </div>
        <div class="col-md-8">
            <div class="tab-content profile-tab" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="row">
                        <div class="col-md-3">
                            <label>Court Type:</label>
                        </div>
                        <div class="col-md-3">
                            <p>@Model.CourtType</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label>Game Type:</label>
                        </div>
                        <div class="col-md-3">
                            <p>@Model.GameType</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label>Description:</label>
                        </div>
                        <div class="col-md-3">
                            <p>@Model.Description</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row-md-12 text-center">
            <a asp-controller="Tournament" asp-action="AddPlayerToTournament" asp-route-tournamentId="@Model.Id" class="btn btn-success">Join</a>
            <a asp-controller="Tournament" asp-action="Bracket" asp-route-id="@Model.Id" class="btn btn-success">Bracket</a>
            <a asp-controller="Match" asp-action="CreateRounds" asp-route-tournamentId="@Model.Id" class="btn btn-success">Start Tournament</a>
        </div>
    </div>
    <h1 class="text-color-green-dark text-center mb-3 mt-5">Joined Players</h1>
    <div class="col">
        <div class="row">
            @foreach (var player in Model.Players)
            {
                <div class="col-md-3 mb-2">
                    <li class="list-group-item d-flex justify-content-between align-content-center">
                        <div class="d-flex flex-row">
                            <img src="/UploadedPhotos/ProfilePhotos/@player.ProfilePhoto" width="40" />
                            <div class="ml-2">
                                <h6 class="text-color-white mb-0">@player.Name</h6>
                                <div class="about">
                                    <span class="text-color-green-dark">Rank: @player.Rank</span>
                                </div>
                            </div>
                        </div>
                    </li>
                </div>
            }
        </div>
    </div>
</div>

Views/Tournament/Edit.cshtml
@model TournamentFormModel

@{
    ViewBag.Title = "Edit Tournament";
}

<partial name="_TournamentFormPartial" model="@Model" />