Models/Player/AddPlayerFormModel.cs
using System.ComponentModel.DataAnnotations;
using TennisTournament.Data.Models;

namespace TennisTournament.Models.Player
{
    public class AddPlayerFormModel
    {
        [Required]
        [StringLength(60, MinimumLength = 3, ErrorMessage = "Name must be in range 3-60 characters!")]
        public string Name { get; set; }

        [Required]
        public int Age { get; set; }

        [Required]
        public Gender Gender { get; init; }

        [Required]
        [Display(Name = "Strong Hand")]
        public StrongHand StrongHand { get; init; }

        [Required]
        [Display(Name = "Back hand stroke")]
        public BackHandStroke BackHandStroke { get; init; }

        [Required(ErrorMessage = "Please choose photo to upload.")]
        [Display(Name = "Upload photo")]
        public IFormFile ProfilePhoto { get; init; }
    }
}

Controllers/ChallengeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TennisTournament.Data.Models;
using TennisTournament.Infrastructure;
using TennisTournament.Models.Challenge;
using TennisTournament.Services.Challenges;
using TennisTournament.Services.Challenges.Models;
using TennisTournament.Services.Players;

namespace TennisTournament.Controllers
{
    public class ChallengeController : Controller
    {
        private readonly IChallengeService challengeService;
        private readonly IPlayerService playerService;

        public ChallengeController(IChallengeService challenge, IPlayerService player)
        {
            this.challengeService = challenge;
            this.playerService = player;
        }

        [HttpGet]
        public IActionResult AddPlayerToChallenge(int id, int challengeId)
        {
            this.challengeService.AddPlayerToChallenge(this.User.GetId(), id, challengeId);

            return RedirectToAction("All", "Player");
        }

        [HttpGet]
        public IActionResult DeleteChallenge(int id)
        {
            this.challengeService.DeleteChallenge(id);

            return RedirectToAction("All", "Player");
        }

        [Authorize]
        public IActionResult CreateChallenge()
        {
            if (!UserIsPlayer())
            {
                return RedirectToAction("AddPlayer", "Player");
            }

            return View(new ChallengeFormModel());
        }

        [HttpPost]
        [Authorize]
        public IActionResult CreateChallenge(ChallengeFormModel challenge, int id)
        {
            if (!ModelState.IsValid)
            {
                return View(challenge);
            }

            var guestId = id;
            var hostUserId = this.User.GetId();

            var challengeData = new Challenge
            {
                Name = challenge.Name,
                CourtType = challenge.CourtTypes,
                Sets = challenge.Sets,
                Games = challenge.Games,
                Rules = challenge.Rules,
                LastSets = challenge.LastSets,
                Description = challenge.Description,
                PlayerHostUserId = hostUserId,
                PlayerGuestId = guestId
            };

            this.challengeService.CreateChallenge(challenge, guestId, hostUserId);

            return RedirectToAction("All", "Player");
        }

        public IActionResult Details(int id)
        {
            var challenge = this.challengeService.Details(id);

            return View(new ChallengeServiceModel
            {
                Id = challenge.Id,
                Name = challenge.Name,
                CourtType = challenge.CourtType,
                Game = challenge.Game,
                Set = challenge.Set,
                Rule = challenge.Rule,
                LastSet = challenge.LastSet,
                Description = challenge.Description,
                Players = challenge.Players
            });
        }

        [Authorize]
        public IActionResult ChallengeResult(ChallengeWinnerFormModel winnerModel, int challengeId)
        {
            this.challengeService.ChallengeResult(challengeId, winnerModel.WinnerId);

            return RedirectToAction("All", "Player");
        }

        public bool UserIsPlayer()
        {
            var userId = this.User.GetId();

            return this.playerService.UserIsPlayer(userId);
        }
    }
}

Controllers/PlayerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TennisTournament.Data.Models;
using TennisTournament.Infrastructure;
using TennisTournament.Infrastructure.Seeder;
using TennisTournament.Models.Player;
using TennisTournament.Services;
using TennisTournament.Services.Players;

namespace TennisTournament.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerService playerService;
        private readonly IUploadFileService uploadFileService;

        public PlayerController(IPlayerService players, IUploadFileService uploadFile)
        {
            this.playerService = players;
            this.uploadFileService = uploadFile;
        }

        [Authorize]
        public async Task<IActionResult> All([FromQuery] AllPlayersQueryModel query)
        {
            var queryResult = await this.playerService.AllAsync(
                query.SearchTerm,
                query.Gender);

            query.TotalPlayers = queryResult.TotalPlayers;
            query.Players = queryResult.Players;

            return View(query);
        }

        public async Task<IActionResult> MyProfile(string userId)
        {
            var player = await this.playerService.FindPlayerByUserIdAsync(userId);

            playerService.DetailsAsync(player.Id);

            return View(new PlayerServiceModel
            {
                Name = player.Name,
                Age = player.Age,
                Gender = player.Gender,
                StrongHand = player.StrongHand,
                BackHandStroke = player.BackHandStroke,
                Rank = player.Rank,
                Wins = player.Wins,
                Losses = player.Losses,
                TotalMatches = player.TotalMatches,
                ProfilePhoto = player.ProfilePhoto,
                Tournaments = player.Tournaments,
                Challenges = player.Challenges,
                UserId = player.UserId
            });
        }

        public async Task<IActionResult> DetailsAsync(int id)
        {
            var player = await this.playerService.DetailsAsync(id);
            var userId = this.User.GetId();

            return View(new PlayerServiceModel
            {
                Id = id,
                Name = player.Name,
                Age = player.Age,
                Gender = player.Gender,
                StrongHand = player.StrongHand,
                BackHandStroke = player.BackHandStroke,
                Rank = player.Rank,
                Wins = player.Wins,
                Losses = player.Losses,
                TotalMatches = player.TotalMatches,
                ProfilePhoto = player.ProfilePhoto,
                Tournaments = player.Tournaments,
                Challenges = player.Challenges,
                UserId = player.UserId
            });
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var deleted = await this.playerService.DeleteAsync(id);

            return RedirectToAction(nameof(All));
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var player = await this.playerService.DetailsAsync(id);

            return View(new PlayerFormModel
            {
                Name = player.Name,
                Age = player.Age,
                Gender = player.Gender,
                StrongHand = player.StrongHand,
                BackHandStroke = player.BackHandStroke
            });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditAsync(int id, PlayerFormModel player)
        {
            if (!ModelState.IsValid)
            {
                return View(player);
            }

            var playerIsEdited = await this.playerService.EditAsync(
                id,
                player.Name,
                player.Age,
                player.Gender,
                player.StrongHand,
                player.BackHandStroke);

            if (!playerIsEdited)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(All));
        }

        [Authorize]
        public IActionResult AddPlayer()
        {
            if (!User.IsInRole(Roles.Administrator) && this.UserIsPlayer())
            {
                return BadRequest();
            }

            return View();
        }

        [HttpPost]
        [Authorize]
        [RequestFormLimits(MultipartBodyLengthLimit = 5242880)]
        [RequestSizeLimit(5242880)]
        public IActionResult AddPlayer(PlayerFormModel player)
        {
            if (this.UserIsPlayer() && User.IsInRole(Roles.User))
            {
                return View(player);
            }

            if (!ModelState.IsValid)
            {
                return View(player);
            }

            if (player.ProfilePhoto == null || !(player.ProfilePhoto.FileName.EndsWith(".jpg")))
            {
                return View(player);
            }

            var userId = this.User.GetId();

            string profilePhoto = this.UploadProfilePhoto(player.ProfilePhoto);

            var playerData = new Player
            {
                Name = player.Name,
                Age = player.Age,
                Gender = player.Gender,
                StrongHand = player.StrongHand,
                BackHandStroke = player.BackHandStroke,
                Rank = player.Rank,
                Wins = player.Wins,
                Losses = player.Losses,
                TotalMatches = player.TotalMatches,
                ProfilePhoto = profilePhoto,
                UserId = userId
            };

            this.playerService.AddPlayer(player, userId, profilePhoto);

            return RedirectToAction(nameof(All));
        }

        public bool UserIsPlayer()
        {
            var userId = this.User.GetId();

            return this.playerService.UserIsPlayer(userId);
        }

        private string UploadProfilePhoto(IFormFile profilePhoto)
        {
            var photo = this.uploadFileService.ProfilePhoto(profilePhoto);

            return photo;
        }
    }
}

Controllers/Tournament/TournamentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TennisTournament.Data.Models;
using TennisTournament.Infrastructure;
using TennisTournament.Models.Tournament;
using TennisTournament.Services;
using TennisTournament.Services.Players;
using TennisTournament.Services.Tournaments;

namespace TennisTournament.Controllers
{
    public class TournamentController : Controller
    {
        private readonly ITournamentService tournamentService;
        private readonly IPlayerService playerService;
        private readonly IUploadFileService uploadFileService;

        public TournamentController(
            ITournamentService tournaments,
            IPlayerService playerService,
            IUploadFileService uploadFile)
        {
            this.tournamentService = tournaments;
            this.playerService = playerService;
            this.uploadFileService = uploadFile;
        }

        public async Task<IActionResult> Bracket(int id)
        {
            var bracket = await this.tournamentService.DetailsAsync(id);

            return View(new TournamentServiceModel
            {
                Id = id,
                Name = bracket.Name,
                MinRank = bracket.MinRank,
                CourtType = bracket.CourtType,
                GameType = bracket.GameType,
                Game = bracket.Game,
                Set = bracket.Set,
                Rule = bracket.Rule,
                LastSet = bracket.LastSet,
                StartDate = bracket.StartDate,
                Description = bracket.Description,
                CoverPhoto = bracket.CoverPhoto,
                Players = bracket.Players,
                Matches = bracket.Matches
            });
        }

        [HttpGet]
        [Authorize]
        public IActionResult AddPlayerToTournament(int tournamentId)
        {
            if (!UserIsPlayer())
            {
                return RedirectToAction("AddPlayer", "Player");
            }

            this.tournamentService.AddPlayerToTournament(this.User.GetId(), tournamentId);

            return RedirectToAction("All", "Player");
        }

        [HttpGet]
        [Authorize]
        public IActionResult RemovePlayerFromTournament(int tournamentId)
        {
            this.tournamentService.RemovePlayerFromTournament(this.User.GetId(), tournamentId);

            return RedirectToAction("All", "Player");

        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var tournament = await this.tournamentService.DetailsAsync(id);

            return View(new TournamentFormModel
            {
                Name = tournament.Name,
                MinRank = tournament.MinRank,
                GameType = tournament.GameType,
                CourtType = tournament.CourtType,
                Set = tournament.Set,
                Game = tournament.Game,
                Rule = tournament.Rule,
                LastSet = tournament.LastSet,
                StartDate = tournament.StartDate,
                Description = tournament.Description
            });
        }

        [HttpPost]
        [Authorize] 
        public async Task<IActionResult> Edit(int id, TournamentFormModel tournament)
        {
            if (!ModelState.IsValid)
            {
                return View(tournament);
            }


            string coverPhoto = this.UploadCoverPhoto(tournament.CoverPhoto);

            var tournamentIsEdited = await this.tournamentService.EditAsync(
                id,
                tournament.Name,
                tournament.MinRank,
                tournament.CourtType,
                tournament.GameType,
                tournament.Set,
                tournament.Game,
                tournament.Rule,
                tournament.LastSet,
                tournament.StartDate,
                tournament.Description);

            if (!tournamentIsEdited)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Details(int id)
        {
            var tournament = await this.tournamentService.DetailsAsync(id);

            return View(new TournamentServiceModel
            {
                Id = id,
                Name = tournament.Name,
                MinRank = tournament.MinRank,
                CourtType = tournament.CourtType,
                GameType = tournament.GameType,
                Game = tournament.Game,
                Set = tournament.Set,
                Rule = tournament.Rule,
                LastSet = tournament.LastSet,
                StartDate = tournament.StartDate,
                Description = tournament.Description,
                CoverPhoto = tournament.CoverPhoto,
                Players = tournament.Players,
                Matches = tournament.Matches
            });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var deleted = await this.tournamentService.DeleteAsync(id);

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> All([FromQuery]AllTournamentsQueryModel query)
        {
            var queryResult = await this.tournamentService.AllAsync(
                query.Name,
                query.SearchTerm,
                query.CourtType,
                query.GameType);

            query.TotalTournaments = queryResult.TotalTournaments;
            query.Tournaments = queryResult.Tournaments;

            return View(query);
        }

        [Authorize]
        public IActionResult AddTournament()
        {
            return View(new TournamentFormModel());
        }

        [HttpPost]
        [Authorize]
        [RequestFormLimits(MultipartBodyLengthLimit = 5242880)]
        [RequestSizeLimit(5242880)]
        public IActionResult AddTournament(TournamentFormModel tournament)
        {
            if (!ModelState.IsValid)
            {
                return View(tournament);
            }

            if (tournament.CoverPhoto == null || !(tournament.CoverPhoto.FileName.EndsWith(".jpg")))
            {
                return View(tournament);
            }

            string coverPhoto = this.UploadCoverPhoto(tournament.CoverPhoto);

            var tournamentData = new Tournament
            {
                Name = tournament.Name,
                MinRank = tournament.MinRank,
                GameType = tournament.GameType,
                CourtType = tournament.CourtType,
                Set = tournament.Set,
                Game = tournament.Game,
                Rule = tournament.Rule,
                LastSet = tournament.LastSet,
                StartDate = tournament.StartDate,
                Description = tournament.Description,
                CoverPhoto = coverPhoto,
            };

            this.tournamentService.CreateTournament(tournament, coverPhoto);

            return RedirectToAction(nameof(All));
        }

        public bool UserIsPlayer()
        {
            var userId = this.User.GetId();

            return this.playerService.UserIsPlayer(userId);
        }

        private string UploadCoverPhoto(IFormFile coverPhoto)
        {
            var photo = this.uploadFileService.CoverPhoto(coverPhoto);

            return photo;
        }
    }
}

Views/Player/Add.cshtml
@model PlayerFormModel

@{
    ViewBag.Title = "Add Player";
}

<partial name="_PlayerFormPartial" model="@Model" />

Views/Player/Details.cshtml
@model PlayerServiceModel

@{
    ViewBag.Title = "Profile";
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var playerId = Model.UserId;
}

<h1 class="text-color-green title text-center">@ViewBag.Title</h1>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/details-form.css" asp-append-version="true" />

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="/UploadedPhotos/ProfilePhotos/@Model.ProfilePhoto" class="img img-responsive">
                </div>
                <div class="col">
                    <div class="row">
                        @if (userId == Model.UserId)
                        {
                            <a asp-controller="Player" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit Profile</a>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        @Model.Name
                    </h5>
                    <h6>
                        Professional tennis player
                    </h6>
                    <p class="proile-rating">
                        Rank: @Model.Rank<br />
                        Wins: @Model.Wins<br />
                        Losses: @Model.Losses<br />
                        Total Matches: @Model.TotalMatches<br />
                        <span></span>
                    </p>
                    <ul class="nav nav-tabs" id="myTab" role="tablist" />
                </div>
            </div>
            <div class="col-md-2">
                <div class="row md-2">
                    @if (userId != Model.UserId)
                    {
                        <a asp-controller="Challenge" asp-action="CreateChallenge" asp-route-id="@Model.Id" class="btn btn-success">Challenge</a>
                    }
                </div>
                @if (User.IsInRole(Roles.Administrator))
                {
                    <a asp-controller="Player" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger mt-3">Delete</a>
                    <a id="invite-button" asp-controller="Player" asp-action="Invite" asp-route-id="@Model.Id" class="btn btn-outline-dark">Invite</a>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>Achievements</p>
                    <a href="">Gold Medal</a><br />
                    <a href="">Silver Medal</a><br />
                    <a href="">Bronze Medal</a><br />
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Gender</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.Gender</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Age</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.Age</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Strong Hand</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.StrongHand</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Back Hand Stroke</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.BackHandStroke</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <h3 class="text-color-green-dark text-center">Tournaments</h3>
            @foreach (var tournament in Model.Tournaments)
            {
                <div class="col-md-6">
                    <div class="card-challenge">
                        <div class="card-body">
                            <h5 class="card-title text-center">@tournament.Name</h5>
                            <p class="card-text text-center">@tournament.Description</p>
                            <a asp-controller="Tournament" asp-action="Details" asp-route-id="@tournament.Id" class="btn btn-outline-dark">Details</a>
                            @if (userId == Model.UserId)
                            {
                                <a asp-controller="Tournament" asp-action="RemovePlayerFromTournament" asp-route-tournamentId="@tournament.Id" class="btn btn-outline-danger">Leave</a>
                            }
                        </div>
                    </div>
                </div>
            }

            <h3 class="text-color-green-dark text-center">Challenges</h3>
            @foreach (var challenge in Model.Challenges)
            {
                <div class="col-md-6">
                    <div class="card-challenge">
                        <div class="card-body">
                            <h5 class="card-title text-center">@challenge.Name</h5>
                            <p class="card-text text-center">@challenge.Description</p>
                            <a asp-controller="Challenge" asp-action="Details" asp-route-id="@challenge.Id" class="btn btn-outline-dark">Details</a>
                            @if (userId == Model.UserId)
                            {
                                <a asp-controller="Challenge" asp-action="DeleteChallenge" asp-route-id="@challenge.Id" class="btn btn-outline-danger">Leave</a>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </form>
</div>

Views/Player/Edit.cshtml
@model PlayerFormModel

@{
    ViewBag.Title = "EditAsync Player";
}

<partial name="_PlayerFormPartial" model="@Model" />

Views/Player/_PlayerDetailsPartial.cshtml
@model PlayerServiceModel

@{
    ViewBag.Title = "Profile";
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var playerId = Model.UserId;
}

<h1 class="text-color-green title text-center">@ViewBag.Title</h1>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/details-form.css" asp-append-version="true" />

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="/UploadedPhotos/ProfilePhotos/@Model.ProfilePhoto" class="img img-responsive">
                </div>
                <div class="col">
                    <div class="row">
                        @if (userId == Model.UserId)
                        {
                            <a asp-controller="Player" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit Profile</a>
                        }
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                    <h5>
                        @Model.Name
                    </h5>
                    <h6>
                        Professional tennis player
                    </h6>
                    <p class="proile-rating">
                        Rank: @Model.Rank<br />
                        Wins: @Model.Wins<br />
                        Losses: @Model.Losses<br />
                        Total Matches: @Model.TotalMatches<br />
                        <span></span>
                    </p>
                    <ul class="nav nav-tabs" id="myTab" role="tablist" />
                </div>
            </div>
            <div class="col-md-2">
                <div class="row md-2">
                    @if (userId != Model.UserId)
                    {
                        <a asp-controller="Challenge" asp-action="CreateChallenge" asp-route-id="@Model.Id" class="btn btn-success">Challenge</a>
                    }
                </div>
                @if (User.IsInRole(Roles.Administrator))
                {
                    <a asp-controller="Player" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger mt-3">Delete</a>
                    <a id="invite-button" asp-controller="Player" asp-action="Invite" asp-route-id="@Model.Id" class="btn btn-outline-dark">Invite</a>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-work">
                    <p>Achievements</p>
                    <a href="">Gold Medal</a><br />
                    <a href="">Silver Medal</a><br />
                    <a href="">Bronze Medal</a><br />
                </div>
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>Gender</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.Gender</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Age</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.Age</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Strong Hand</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.StrongHand</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Back Hand Stroke</label>
                            </div>
                            <div class="col-md-6">
                                <p>@Model.BackHandStroke</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <h3 class="text-color-green-dark text-center">Tournaments</h3>
            @foreach (var tournament in Model.Tournaments)
            {
                <div class="col-md-6">
                    <div class="card-challenge">
                        <div class="card-body">
                            <h5 class="card-title text-center">@tournament.Name</h5>
                            <p class="card-text text-center">@tournament.Description</p>
                            <a asp-controller="Tournament" asp-action="Details" asp-route-id="@tournament.Id" class="btn btn-outline-dark">Details</a>
                            @if (userId == Model.UserId)
                            {
                                <a asp-controller="Tournament" asp-action="RemovePlayerFromTournament" asp-route-tournamentId="@tournament.Id" class="btn btn-outline-danger">Leave</a>
                            }
                        </div>
                    </div>
                </div>
            }

            <h3 class="text-color-green-dark text-center">Challenges</h3>
            @foreach (var challenge in Model.Challenges)
            {
                <div class="col-md-6">
                    <div class="card-challenge">
                        <div class="card-body">
                            <h5 class="card-title text-center">@challenge.Name</h5>
                            <p class="card-text text-center">@challenge.Description</p>
                            <a asp-controller="Challenge" asp-action="Details" asp-route-id="@challenge.Id" class="btn btn-outline-dark">Details</a>
                            @if (userId == Model.UserId)
                            {
                                <a asp-controller="Challenge" asp-action="DeleteChallenge" asp-route-id="@challenge.Id" class="btn btn-outline-danger">Leave</a>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </form>
</div>